version: '3'

services:
  server:
    build:
      context: .
      dockerfile: docker/server.dockerfile
    image: word-ofwisdom/server:latest
    container_name: server-wow
    restart: always

  client:
    build:
      context: .
      dockerfile: docker/client.dockerfile
    image: word-of-wisdomclient:latest
    container_name: client-wow
    environment:
      - SERVER_ADDR=server:8080
    depends_on:
      - server